resources:
- repo: self
  clean: true
trigger:
  batch: true
  branches:
    include:
    - master
schedules:
- cron: "0 17 * * Fri"
  always: true
  displayName: Weekly build
  branches:
    include:
    - master
pool:
  vmImage: 'windows-latest'
variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - group: 'Deployment Credentials'
  - name: ResourceGroupName
    value: 'letsencrypt-inttest'

steps:
- checkout: self

- task: AzurePowerShell@4
  displayName: 'Deploy'
  inputs:
    azureSubscription: 'Opensource Deployments'
    ScriptPath: '$(System.DefaultWorkingDirectory)/deploy/Deploy.ps1'
    ScriptArguments: '-ResourceGroupName $(ResourceGroupName) -File integration.json'
    azurePowerShellVersion: LatestVersion
